version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
executors:
  default-executor:
    docker:
      - image: cirrusci/flutter:stable
    resource_class: large
    shell: /bin/bash
jobs:
  build:
    executor: default-executor
    steps:
      - checkout
      - run: flutter --version
      - run:
          name: Set up environment
          command: |
            echo 'export PATH=$HOME/.pub-cache/bin:$PATH' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Setup melos
          command: |
            flutter pub global activate melos
            melos --version
            melos bootstrap
      - run:
          name: Run Test Suite
          command: melos run test
      - run:
          name: Generate Coverage Report
          command: melos run gen_coverage
      - codecov/upload:
          file: coverage_report/lcov.info
      - run:
          name: Run flutter analyze
          command: melos run analyze
      - run:
          name: Check That Flutter Code is Formatted Correctly
          command: flutter format -o none --set-exit-if-changed .
