version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
    - image: cirrusci/flutter
    steps:
    - checkout
    - run: flutter --version
    - run: flutter test --coverage
    - codecov/upload:
        file: coverage/lcov.info
