name: flutter_html_audio
description: This extension package allows the <audio> tag to be rendered using the flutter_html package
version: 3.0.0-alpha.4
homepage: https://github.com/Sub6Resources/flutter_html

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
  html: '>=0.15.0 <1.0.0'
  flutter_html: ^3.0.0-alpha.6
#  flutter_html:
#    path: ../..

  video_player: '>=2.2.8 <3.0.0'
  chewie_audio: '>=1.3.0 <2.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
