name: flutter_html_audio
description: This extension package allows the <audio> tag to be rendered using the flutter_html package
version: 3.0.0-beta.2
homepage: https://github.com/Sub6Resources/flutter_html

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
  html: '>=0.15.0 <1.0.0'
  flutter_html: ^3.0.0-beta.2
  video_player: '>=2.2.8 <3.0.0'
  chewie_audio: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

funding:
  - https://opencollective.com/flutter_html

topics:
  - html
  - css
  - audio
  - layout
  - flutter_html
